[files]
english = "scripts/wordlists/english.txt"
bad_words = "scripts/wordlists/bad.txt"
vectors = "GoogleNews-vectors-negative300.bin"

[database]
# For postgres: "postgresql+asyncpg://<user>:<password>@<hostname>:<port>"
# For sqlite3: "sqlite+aiosqlite:///<path/to/database.db>"
# For in-memory: "sqlite+aiosqlite:///:memory:"

uri = "sqlite+aiosqlite:///similarium.db"

[logging]
log_level = "INFO"
web_log_level = "WARNING"

[slack]
dev_mode = true
bot_token = "<BOT_TOKEN>"  # Only required in dev_mode
app_token = "<APP_TOKEN>"
client_id = "<CLIENT_ID>"
client_secret = "<CLIENT_SECRET>"
signing_secret = "<SIGNING_SECRET>"
scopes = ["commands", "users:read", "chat:write"]

[slack.server]
port = 3000
host = "127.0.0.1"
path = "/slack/events"

[sentry]
dsn = "<SENTRY_DSN>"
env = "dev"

[rules]
similarity_count = 1000

[hints]
enabled = true
threshold = 100

[hints.openai]
api_key = "<OPENAI_API_KEY>"
api_url = "https://api.openai.com/v1/chat/completions"
temperature = 1.2
