[files]
english = "scripts/wordlists/english.txt"
bad_words = "scripts/wordlists/bad.txt"
vectors = "GoogleNews-vectors-negative300.bin"

[database]
# For postgres: "postgresql+asyncpg://<user>:<password>@<hostname>:<port>"
# For sqlite3: "sqlite+aiosqlite:///path/to/database.db>"
# For in-memory: "sqlite+aiosqlite:///:memory:"
uri = "postgresql+asyncpg://postgres:s3cr3t@localhost:5432"

[rules]
similarity_count = 1000
