[tool.poetry]
name = "semantle-slack-bot"
version = "0.1.0"
description = "A Slack bot to play Semantle together as a team"
authors = ["Axel <dev@absalon.is>"]
license = "GNU GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
gensim = "^4.1.2"
numpy = "^1.22.3"
slack-sdk = "^3.15.2"
slack-bolt = "^1.13.0"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.3.0"
pyright = "^1.1.237"
flake8 = "^4.0.1"
flake8-builtins = "^1.5.3"
flake8-isort = "^4.1.1"
flake8-bugbear = "^22.3.23"
flake8-black = "^0.3.2"
flake8-annotations = "^2.8.0"
ipdb = "^0.13.9"
pdbpp = "^0.10.3"
pytest = "^7.1.1"
pytest-clarity = "^1.0.1"
rich = "^12.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
