[tool.poetry]
name = "semantle-slack-bot"
version = "0.1.0"
description = "A Slack bot to play Semantle together as a team"
authors = ["Axel <dev@absalon.is>"]
license = "GNU GPLv3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
