version: "3.9"

services:
  similarium:
    image: absalon/similarium:1.1.1-sqlite
    volumes:
      - ../config.toml:/app/config.toml
      - ../similarium.db:/app/similarium.db
      - ../data:/app/data/
    ports:
      - "127.0.0.1:3000:3000"
